name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    needs:
      - publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Drafts your next Release notes as Pull Requests are merged into "main"
      - name: Create release
        id: create-release
        uses: release-drafter/release-drafter@v5
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: release-drafter.yaml
          publish: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

